### ISSUE TITLE
这个问题是 webpack 配置错误导致的

### ISSUE THREAD

**Issue by luckyyyyy** [satsuya0114/react-webpack-startkit-babel-7#2]
在一个月前，我也遇到了同样的问题，仔细阅读文档后，发现错误。
``` 
path.resolve(__dirname, 'node_modules/'),
```
改为 
```
/node_modules/
```

@satsuya0114 
@afc163 

https://github.com/satsuya0114/react-webpack-startkit-babel-7/blob/master/webpack.common.js#L93

**Comment by satsuya0114** [comment]
@luckyyyyy Thanks a lot!!! :)
